package com.ardikars.opennetcut.view;

@SuppressWarnings("deprecation")
public class MainWindow extends javax.swing.JFrame {   
    
    public static MainWindow main_windows = new MainWindow();

    private MainWindow() {
        initComponents();
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TargetPanel = new javax.swing.JPanel();
        TargetSP = new javax.swing.JScrollPane();
        TargetTable = new javax.swing.JTable();
        btn_cut = new javax.swing.JButton();
        btn_mitm = new javax.swing.JButton();
        btn_move_to_left = new javax.swing.JButton();
        btn_target_check = new javax.swing.JButton();
        ScanPanel = new javax.swing.JPanel();
        ScanSP = new javax.swing.JScrollPane();
        ScanTable = new javax.swing.JTable();
        btn_scan = new javax.swing.JButton();
        cb_scan_by = new javax.swing.JComboBox();
        lbl_find_by = new javax.swing.JLabel();
        txt_input_find = new javax.swing.JTextField();
        btn_scan_check = new javax.swing.JButton();
        btn_move_to_right = new javax.swing.JButton();
        lbl_nic_name = new javax.swing.JLabel();
        lbl_hw_addr = new javax.swing.JLabel();
        txt_nic_name = new javax.swing.JTextField();
        txt_hw_addr = new javax.swing.JTextField();
        LogsSP = new javax.swing.JScrollPane();
        txt_logs = new javax.swing.JTextArea();
        LogoPanel = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_jxnet = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        Toolbar = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        OpenIcon = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        SaveIcon = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        SettingIcon = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        WifiIcon = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        HelpIcon = new javax.swing.JLabel();
        MainMenu = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenMenu = new javax.swing.JMenuItem();
        SaveMenu = new javax.swing.JMenuItem();
        ExitMenu = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        NICMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        UpdateMenu = new javax.swing.JMenuItem();
        AboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenNetcut");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        TargetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("[ Attack ]"));

        TargetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TargetSP.setViewportView(TargetTable);

        btn_cut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/edit-cut.png"))); // NOI18N
        btn_cut.setText("Cut");
        btn_cut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cutActionPerformed(evt);
            }
        });

        btn_mitm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/network-idle.png"))); // NOI18N
        btn_mitm.setText("MITM");
        btn_mitm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mitmActionPerformed(evt);
            }
        });

        btn_move_to_left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/go-next-rtl.png"))); // NOI18N
        btn_move_to_left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_move_to_leftActionPerformed(evt);
            }
        });

        btn_target_check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/zoom-in.png"))); // NOI18N
        btn_target_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_target_checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TargetPanelLayout = new javax.swing.GroupLayout(TargetPanel);
        TargetPanel.setLayout(TargetPanelLayout);
        TargetPanelLayout.setHorizontalGroup(
            TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TargetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TargetSP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(TargetPanelLayout.createSequentialGroup()
                        .addGroup(TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cut, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(btn_move_to_left, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_mitm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_target_check, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        TargetPanelLayout.setVerticalGroup(
            TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TargetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cut)
                    .addComponent(btn_mitm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_move_to_left)
                    .addComponent(btn_target_check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TargetSP, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        ScanPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("[ Network Client ]"));

        ScanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ScanTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ScanTableComponentResized(evt);
            }
        });
        ScanSP.setViewportView(ScanTable);

        btn_scan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/media-playback-start.png"))); // NOI18N
        btn_scan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scanActionPerformed(evt);
            }
        });

        cb_scan_by.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auto", "IP Address" }));
        cb_scan_by.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_scan_byActionPerformed(evt);
            }
        });

        lbl_find_by.setText("Find target by");

        txt_input_find.setEditable(false);

        btn_scan_check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/zoom-in.png"))); // NOI18N
        btn_scan_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scan_checkActionPerformed(evt);
            }
        });

        btn_move_to_right.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/go-next.png"))); // NOI18N
        btn_move_to_right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_move_to_rightActionPerformed(evt);
            }
        });

        lbl_nic_name.setText("NIC Name");

        lbl_hw_addr.setText("Hardware Address");

        txt_nic_name.setEditable(false);

        txt_hw_addr.setEditable(false);

        javax.swing.GroupLayout ScanPanelLayout = new javax.swing.GroupLayout(ScanPanel);
        ScanPanel.setLayout(ScanPanelLayout);
        ScanPanelLayout.setHorizontalGroup(
            ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScanSP)
                    .addGroup(ScanPanelLayout.createSequentialGroup()
                        .addGroup(ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_find_by)
                            .addComponent(lbl_nic_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ScanPanelLayout.createSequentialGroup()
                                .addComponent(cb_scan_by, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_input_find, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                            .addComponent(txt_nic_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ScanPanelLayout.createSequentialGroup()
                                .addComponent(btn_scan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_scan_check, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_move_to_right, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ScanPanelLayout.createSequentialGroup()
                                .addComponent(lbl_hw_addr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_hw_addr)))))
                .addContainerGap())
        );
        ScanPanelLayout.setVerticalGroup(
            ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nic_name)
                    .addComponent(lbl_hw_addr)
                    .addComponent(txt_nic_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hw_addr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_scan)
                    .addComponent(cb_scan_by, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_find_by)
                    .addComponent(txt_input_find, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_scan_check)
                    .addComponent(btn_move_to_right))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScanSP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        txt_logs.setEditable(false);
        txt_logs.setColumns(20);
        txt_logs.setRows(5);
        LogsSP.setViewportView(txt_logs);

        lbl_logo.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_logo.setText(" [ OpenNetcut ] ");

        lbl_jxnet.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        lbl_jxnet.setText("Powered by Jxnet");

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_jxnet)
                .addGap(167, 167, 167))
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_jxnet)
                .addGap(6, 6, 6))
        );

        progress.setMaximum(255);
        progress.setString("");
        progress.setStringPainted(true);

        Toolbar.setFloatable(false);
        Toolbar.setBorderPainted(false);
        Toolbar.add(filler1);

        OpenIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/32x32/document-open.png"))); // NOI18N
        Toolbar.add(OpenIcon);
        Toolbar.add(filler2);

        SaveIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/32x32/document-save.png"))); // NOI18N
        Toolbar.add(SaveIcon);
        Toolbar.add(filler4);

        SettingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/32x32/applications-system.png"))); // NOI18N
        Toolbar.add(SettingIcon);
        Toolbar.add(filler5);

        WifiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/32x32/network-wireless.png"))); // NOI18N
        Toolbar.add(WifiIcon);
        Toolbar.add(filler6);

        HelpIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/32x32/help-browser.png"))); // NOI18N
        Toolbar.add(HelpIcon);

        FileMenu.setText("File");

        OpenMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/document-open.png"))); // NOI18N
        OpenMenu.setText("Open");
        OpenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMenuActionPerformed(evt);
            }
        });
        FileMenu.add(OpenMenu);

        SaveMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/document-save.png"))); // NOI18N
        SaveMenu.setText("Save");
        SaveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveMenuActionPerformed(evt);
            }
        });
        FileMenu.add(SaveMenu);

        ExitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/window-close.png"))); // NOI18N
        ExitMenu.setText("Exit");
        ExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuActionPerformed(evt);
            }
        });
        FileMenu.add(ExitMenu);

        MainMenu.add(FileMenu);

        EditMenu.setText("Edit");

        NICMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        NICMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/applications-system.png"))); // NOI18N
        NICMenu.setText("Network Interface Card");
        NICMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICMenuActionPerformed(evt);
            }
        });
        EditMenu.add(NICMenu);

        MainMenu.add(EditMenu);

        HelpMenu.setText("Help");

        UpdateMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        UpdateMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/system-software-update.png"))); // NOI18N
        UpdateMenu.setText("Check For Update");
        UpdateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMenuActionPerformed(evt);
            }
        });
        HelpMenu.add(UpdateMenu);

        AboutMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        AboutMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/help-browser.png"))); // NOI18N
        AboutMenu.setText("About");
        AboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutMenuActionPerformed(evt);
            }
        });
        HelpMenu.add(AboutMenu);

        MainMenu.add(HelpMenu);

        setJMenuBar(MainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogsSP)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ScanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TargetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TargetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogsSP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_scanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scanActionPerformed
    }//GEN-LAST:event_btn_scanActionPerformed

    private void NICMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICMenuActionPerformed
    }//GEN-LAST:event_NICMenuActionPerformed

    private void ScanTableComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ScanTableComponentResized
    }//GEN-LAST:event_ScanTableComponentResized

    private void cb_scan_byActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_scan_byActionPerformed
    }//GEN-LAST:event_cb_scan_byActionPerformed

    private void btn_move_to_rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_move_to_rightActionPerformed
       
    }//GEN-LAST:event_btn_move_to_rightActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

    private void btn_move_to_leftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_move_to_leftActionPerformed
    }//GEN-LAST:event_btn_move_to_leftActionPerformed

    private void btn_scan_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scan_checkActionPerformed
    }//GEN-LAST:event_btn_scan_checkActionPerformed

    private void btn_target_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_target_checkActionPerformed
    }//GEN-LAST:event_btn_target_checkActionPerformed

    private void btn_cutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cutActionPerformed
    }//GEN-LAST:event_btn_cutActionPerformed

    private void btn_mitmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mitmActionPerformed
    }//GEN-LAST:event_btn_mitmActionPerformed

    private void SaveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveMenuActionPerformed
    }//GEN-LAST:event_SaveMenuActionPerformed

    private void OpenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMenuActionPerformed
    }//GEN-LAST:event_OpenMenuActionPerformed
    
    private void ExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuActionPerformed
    }//GEN-LAST:event_ExitMenuActionPerformed

    private void AboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutMenuActionPerformed
    }//GEN-LAST:event_AboutMenuActionPerformed

    private void UpdateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMenuActionPerformed
    }//GEN-LAST:event_UpdateMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenu;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenuItem ExitMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JLabel HelpIcon;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JScrollPane LogsSP;
    private javax.swing.JMenuBar MainMenu;
    private javax.swing.JMenuItem NICMenu;
    private javax.swing.JLabel OpenIcon;
    private javax.swing.JMenuItem OpenMenu;
    private javax.swing.JLabel SaveIcon;
    private javax.swing.JMenuItem SaveMenu;
    private javax.swing.JPanel ScanPanel;
    private javax.swing.JScrollPane ScanSP;
    private javax.swing.JTable ScanTable;
    private javax.swing.JLabel SettingIcon;
    private javax.swing.JPanel TargetPanel;
    private javax.swing.JScrollPane TargetSP;
    private javax.swing.JTable TargetTable;
    private javax.swing.JToolBar Toolbar;
    private javax.swing.JMenuItem UpdateMenu;
    private javax.swing.JLabel WifiIcon;
    private javax.swing.JButton btn_cut;
    private javax.swing.JButton btn_mitm;
    private javax.swing.JButton btn_move_to_left;
    private javax.swing.JButton btn_move_to_right;
    private javax.swing.JButton btn_scan;
    private javax.swing.JButton btn_scan_check;
    private javax.swing.JButton btn_target_check;
    private javax.swing.JComboBox cb_scan_by;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel lbl_find_by;
    private javax.swing.JLabel lbl_hw_addr;
    private javax.swing.JLabel lbl_jxnet;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nic_name;
    private javax.swing.JProgressBar progress;
    private javax.swing.JTextField txt_hw_addr;
    private javax.swing.JTextField txt_input_find;
    private javax.swing.JTextArea txt_logs;
    private javax.swing.JTextField txt_nic_name;
    // End of variables declaration//GEN-END:variables

}
