package com.ardikars.opennetcut.view;

import com.ardikars.jxnet.exception.JxnetException;
import com.ardikars.jxnet.util.AddrUtils;
import com.ardikars.opennetcut.app.Utils;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

@SuppressWarnings("deprecation")
public class MainWindow extends javax.swing.JFrame {   
    
    public static MainWindow main_windows = new MainWindow();
    
    private String source;
    
    private DefaultTableModel scanTable;
    private DefaultTableModel targetTable;

    private MainWindow() {
        initComponents();
        source = Utils.getDeviceName();
        scanTable = Utils.createDefaultTableModel(new String[] {"No", "Add", "IP Address", "MAC Address"});
        targetTable = Utils.createDefaultTableModel(new String[] {"IP Address","Add"});
        ScanTable.setModel(scanTable);
        TargetTable.setModel(targetTable);
        ScanTable.getColumnModel().getColumn(0).setMaxWidth(100);
        ScanTable.getColumnModel().getColumn(1).setMaxWidth(100);
        TargetTable.getColumnModel().getColumn(1).setMaxWidth(100);
        _txt_NICName.setText(source);
        _txtHwAddr.setText(AddrUtils.getHardwareAddress(source).toString());
    }    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _TargetPanel = new javax.swing.JPanel();
        _TargetSP = new javax.swing.JScrollPane();
        TargetTable = new javax.swing.JTable();
        _btnCut = new javax.swing.JButton();
        _btnMITM = new javax.swing.JButton();
        _btnMoveToLeft = new javax.swing.JButton();
        _btnAddTarget = new javax.swing.JButton();
        ScanPanel = new javax.swing.JPanel();
        _ScanSP = new javax.swing.JScrollPane();
        ScanTable = new javax.swing.JTable();
        _btnScan = new javax.swing.JButton();
        _cbScanBy = new javax.swing.JComboBox();
        _lblFindBy = new javax.swing.JLabel();
        _txtInputFind = new javax.swing.JTextField();
        _btnScanAddToTarget = new javax.swing.JButton();
        _btnMoveToRight = new javax.swing.JButton();
        _lblNICName = new javax.swing.JLabel();
        _lblHwAddr = new javax.swing.JLabel();
        _txt_NICName = new javax.swing.JTextField();
        _txtHwAddr = new javax.swing.JTextField();
        _LogsSP = new javax.swing.JScrollPane();
        _txt_logs = new javax.swing.JTextArea();
        _LogoPanel = new javax.swing.JPanel();
        _lblLogo = new javax.swing.JLabel();
        _lblJxnet = new javax.swing.JLabel();
        _progressBar = new javax.swing.JProgressBar();
        _Toolbar = new javax.swing.JToolBar();
        _filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        _OpenIcon = new javax.swing.JLabel();
        _filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        _SaveIcon = new javax.swing.JLabel();
        _filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        _SettingIcon = new javax.swing.JLabel();
        _filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        _WifiIcon = new javax.swing.JLabel();
        _filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        _HelpIcon = new javax.swing.JLabel();
        _MenuBar = new javax.swing.JMenuBar();
        _FileMenu = new javax.swing.JMenu();
        _OpenMenu = new javax.swing.JMenuItem();
        _SaveMenu = new javax.swing.JMenuItem();
        _ExitMenu = new javax.swing.JMenuItem();
        _EditMenu = new javax.swing.JMenu();
        _NICMenu = new javax.swing.JMenuItem();
        _PluginsMenu = new javax.swing.JMenu();
        _DNSSpoofPluginMenu = new javax.swing.JCheckBoxMenuItem();
        _SSLSniffPluginMenu = new javax.swing.JCheckBoxMenuItem();
        _NDPSupport = new javax.swing.JCheckBoxMenuItem();
        _HelpMenu = new javax.swing.JMenu();
        _UpdateMenu = new javax.swing.JMenuItem();
        _AboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenNetcut");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        _TargetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("[ Attack ]"));

        TargetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        _TargetSP.setViewportView(TargetTable);

        _btnCut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/edit-cut.png"))); // NOI18N
        _btnCut.setText("Cut");
        _btnCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnCutActionPerformed(evt);
            }
        });

        _btnMITM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/network-idle.png"))); // NOI18N
        _btnMITM.setText("MITM");
        _btnMITM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnMITMActionPerformed(evt);
            }
        });

        _btnMoveToLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/go-next-rtl.png"))); // NOI18N
        _btnMoveToLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnMoveToLeftActionPerformed(evt);
            }
        });

        _btnAddTarget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/zoom-in.png"))); // NOI18N
        _btnAddTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnAddTargetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout _TargetPanelLayout = new javax.swing.GroupLayout(_TargetPanel);
        _TargetPanel.setLayout(_TargetPanelLayout);
        _TargetPanelLayout.setHorizontalGroup(
            _TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_TargetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_TargetSP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(_TargetPanelLayout.createSequentialGroup()
                        .addGroup(_TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(_btnCut, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(_btnMoveToLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(_TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_btnMITM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_btnAddTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        _TargetPanelLayout.setVerticalGroup(
            _TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _TargetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btnCut)
                    .addComponent(_btnMITM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(_TargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btnMoveToLeft)
                    .addComponent(_btnAddTarget))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_TargetSP, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        ScanPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("[ Network Client ]"));

        ScanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ScanTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ScanTableComponentResized(evt);
            }
        });
        _ScanSP.setViewportView(ScanTable);

        _btnScan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/media-playback-start.png"))); // NOI18N
        _btnScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnScanActionPerformed(evt);
            }
        });

        _cbScanBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auto", "IP Address" }));
        _cbScanBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _cbScanByActionPerformed(evt);
            }
        });

        _lblFindBy.setText("Find target by");

        _txtInputFind.setEditable(false);

        _btnScanAddToTarget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/zoom-in.png"))); // NOI18N
        _btnScanAddToTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnScanAddToTargetActionPerformed(evt);
            }
        });

        _btnMoveToRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/go-next.png"))); // NOI18N
        _btnMoveToRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnMoveToRightActionPerformed(evt);
            }
        });

        _lblNICName.setText("NIC Name");

        _lblHwAddr.setText("Hardware Address");

        _txt_NICName.setEditable(false);

        _txtHwAddr.setEditable(false);

        javax.swing.GroupLayout ScanPanelLayout = new javax.swing.GroupLayout(ScanPanel);
        ScanPanel.setLayout(ScanPanelLayout);
        ScanPanelLayout.setHorizontalGroup(
            ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_ScanSP)
                    .addGroup(ScanPanelLayout.createSequentialGroup()
                        .addGroup(ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_lblFindBy)
                            .addComponent(_lblNICName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ScanPanelLayout.createSequentialGroup()
                                .addComponent(_cbScanBy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_txtInputFind, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                            .addComponent(_txt_NICName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ScanPanelLayout.createSequentialGroup()
                                .addComponent(_btnScan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_btnScanAddToTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_btnMoveToRight, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ScanPanelLayout.createSequentialGroup()
                                .addComponent(_lblHwAddr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_txtHwAddr)))))
                .addContainerGap())
        );
        ScanPanelLayout.setVerticalGroup(
            ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lblNICName)
                    .addComponent(_lblHwAddr)
                    .addComponent(_txt_NICName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_txtHwAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ScanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btnScan)
                    .addComponent(_cbScanBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_lblFindBy)
                    .addComponent(_txtInputFind, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_btnScanAddToTarget)
                    .addComponent(_btnMoveToRight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_ScanSP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        _txt_logs.setEditable(false);
        _txt_logs.setColumns(20);
        _txt_logs.setRows(5);
        _LogsSP.setViewportView(_txt_logs);

        _lblLogo.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        _lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        _lblLogo.setText(" [ OpenNetcut ] ");

        _lblJxnet.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        _lblJxnet.setText("Powered by Jxnet");

        javax.swing.GroupLayout _LogoPanelLayout = new javax.swing.GroupLayout(_LogoPanel);
        _LogoPanel.setLayout(_LogoPanelLayout);
        _LogoPanelLayout.setHorizontalGroup(
            _LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_LogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _LogoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_lblJxnet)
                .addGap(167, 167, 167))
        );
        _LogoPanelLayout.setVerticalGroup(
            _LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_LogoPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(_lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lblJxnet)
                .addGap(6, 6, 6))
        );

        _progressBar.setMaximum(255);
        _progressBar.setString("");
        _progressBar.setStringPainted(true);

        _Toolbar.setFloatable(false);
        _Toolbar.setBorderPainted(false);
        _Toolbar.add(_filler1);

        _OpenIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/32x32/document-open.png"))); // NOI18N
        _Toolbar.add(_OpenIcon);
        _Toolbar.add(_filler2);

        _SaveIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/32x32/document-save.png"))); // NOI18N
        _Toolbar.add(_SaveIcon);
        _Toolbar.add(_filler4);

        _SettingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/32x32/applications-system.png"))); // NOI18N
        _Toolbar.add(_SettingIcon);
        _Toolbar.add(_filler5);

        _WifiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/32x32/network-wireless.png"))); // NOI18N
        _Toolbar.add(_WifiIcon);
        _Toolbar.add(_filler6);

        _HelpIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/32x32/help-browser.png"))); // NOI18N
        _Toolbar.add(_HelpIcon);

        _FileMenu.setText("File");

        _OpenMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        _OpenMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/document-open.png"))); // NOI18N
        _OpenMenu.setText("Open");
        _OpenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _OpenMenuActionPerformed(evt);
            }
        });
        _FileMenu.add(_OpenMenu);

        _SaveMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        _SaveMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/document-save.png"))); // NOI18N
        _SaveMenu.setText("Save");
        _SaveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _SaveMenuActionPerformed(evt);
            }
        });
        _FileMenu.add(_SaveMenu);

        _ExitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/window-close.png"))); // NOI18N
        _ExitMenu.setText("Exit");
        _ExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _ExitMenuActionPerformed(evt);
            }
        });
        _FileMenu.add(_ExitMenu);

        _MenuBar.add(_FileMenu);

        _EditMenu.setText("Edit");

        _NICMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        _NICMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/applications-system.png"))); // NOI18N
        _NICMenu.setText("Network Interface Card");
        _NICMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _NICMenuActionPerformed(evt);
            }
        });
        _EditMenu.add(_NICMenu);

        _MenuBar.add(_EditMenu);

        _PluginsMenu.setText("Plugins");

        _DNSSpoofPluginMenu.setSelected(true);
        _DNSSpoofPluginMenu.setText("DNSSpoof");
        _PluginsMenu.add(_DNSSpoofPluginMenu);

        _SSLSniffPluginMenu.setSelected(true);
        _SSLSniffPluginMenu.setText("SSLSniff");
        _PluginsMenu.add(_SSLSniffPluginMenu);

        _NDPSupport.setSelected(true);
        _NDPSupport.setText("NDPSupport");
        _PluginsMenu.add(_NDPSupport);

        _MenuBar.add(_PluginsMenu);

        _HelpMenu.setText("Help");

        _UpdateMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        _UpdateMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/system-software-update.png"))); // NOI18N
        _UpdateMenu.setText("Check For Update");
        _UpdateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _UpdateMenuActionPerformed(evt);
            }
        });
        _HelpMenu.add(_UpdateMenu);

        _AboutMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        _AboutMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ardikars/opennetcut/images/16x16/help-browser.png"))); // NOI18N
        _AboutMenu.setText("About");
        _AboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _AboutMenuActionPerformed(evt);
            }
        });
        _HelpMenu.add(_AboutMenu);

        _MenuBar.add(_HelpMenu);

        setJMenuBar(_MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_LogsSP)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ScanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_TargetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(_progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(_Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(_Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_TargetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_LogsSP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btnScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnScanActionPerformed
    }//GEN-LAST:event__btnScanActionPerformed

    private void _NICMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__NICMenuActionPerformed
        try {
            new NIC(source, 1500, 1, 1500).setVisible(true);
        } catch (JxnetException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event__NICMenuActionPerformed

    private void ScanTableComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ScanTableComponentResized
    }//GEN-LAST:event_ScanTableComponentResized

    private void _cbScanByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__cbScanByActionPerformed
    }//GEN-LAST:event__cbScanByActionPerformed

    private void _btnMoveToRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnMoveToRightActionPerformed
       
    }//GEN-LAST:event__btnMoveToRightActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

    private void _btnMoveToLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnMoveToLeftActionPerformed
    }//GEN-LAST:event__btnMoveToLeftActionPerformed

    private void _btnScanAddToTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnScanAddToTargetActionPerformed
    }//GEN-LAST:event__btnScanAddToTargetActionPerformed

    private void _btnAddTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnAddTargetActionPerformed
    }//GEN-LAST:event__btnAddTargetActionPerformed

    private void _btnCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnCutActionPerformed
    }//GEN-LAST:event__btnCutActionPerformed

    private void _btnMITMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnMITMActionPerformed
    }//GEN-LAST:event__btnMITMActionPerformed

    private void _SaveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__SaveMenuActionPerformed
    }//GEN-LAST:event__SaveMenuActionPerformed

    private void _OpenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__OpenMenuActionPerformed
    }//GEN-LAST:event__OpenMenuActionPerformed
    
    private void _ExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__ExitMenuActionPerformed
    }//GEN-LAST:event__ExitMenuActionPerformed

    private void _AboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__AboutMenuActionPerformed
    }//GEN-LAST:event__AboutMenuActionPerformed

    private void _UpdateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__UpdateMenuActionPerformed
    }//GEN-LAST:event__UpdateMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ScanPanel;
    private javax.swing.JTable ScanTable;
    private javax.swing.JTable TargetTable;
    private javax.swing.JMenuItem _AboutMenu;
    private javax.swing.JCheckBoxMenuItem _DNSSpoofPluginMenu;
    private javax.swing.JMenu _EditMenu;
    private javax.swing.JMenuItem _ExitMenu;
    private javax.swing.JMenu _FileMenu;
    private javax.swing.JLabel _HelpIcon;
    private javax.swing.JMenu _HelpMenu;
    private javax.swing.JPanel _LogoPanel;
    private javax.swing.JScrollPane _LogsSP;
    private javax.swing.JMenuBar _MenuBar;
    private javax.swing.JCheckBoxMenuItem _NDPSupport;
    private javax.swing.JMenuItem _NICMenu;
    private javax.swing.JLabel _OpenIcon;
    private javax.swing.JMenuItem _OpenMenu;
    private javax.swing.JMenu _PluginsMenu;
    private javax.swing.JCheckBoxMenuItem _SSLSniffPluginMenu;
    private javax.swing.JLabel _SaveIcon;
    private javax.swing.JMenuItem _SaveMenu;
    private javax.swing.JScrollPane _ScanSP;
    private javax.swing.JLabel _SettingIcon;
    private javax.swing.JPanel _TargetPanel;
    private javax.swing.JScrollPane _TargetSP;
    private javax.swing.JToolBar _Toolbar;
    private javax.swing.JMenuItem _UpdateMenu;
    private javax.swing.JLabel _WifiIcon;
    private javax.swing.JButton _btnAddTarget;
    private javax.swing.JButton _btnCut;
    private javax.swing.JButton _btnMITM;
    private javax.swing.JButton _btnMoveToLeft;
    private javax.swing.JButton _btnMoveToRight;
    private javax.swing.JButton _btnScan;
    private javax.swing.JButton _btnScanAddToTarget;
    private javax.swing.JComboBox _cbScanBy;
    private javax.swing.Box.Filler _filler1;
    private javax.swing.Box.Filler _filler2;
    private javax.swing.Box.Filler _filler4;
    private javax.swing.Box.Filler _filler5;
    private javax.swing.Box.Filler _filler6;
    private javax.swing.JLabel _lblFindBy;
    private javax.swing.JLabel _lblHwAddr;
    private javax.swing.JLabel _lblJxnet;
    private javax.swing.JLabel _lblLogo;
    private javax.swing.JLabel _lblNICName;
    private javax.swing.JProgressBar _progressBar;
    private javax.swing.JTextField _txtHwAddr;
    private javax.swing.JTextField _txtInputFind;
    private javax.swing.JTextField _txt_NICName;
    private javax.swing.JTextArea _txt_logs;
    // End of variables declaration//GEN-END:variables

}
